
server:
  port: 9092

security:
  oauth2:
    client:
      client-id: ci
      client-secret: sc
      access-token-uri: http://localhost:9090/app/oauth/token
      user-authorization-uri: http://localhost:9090/app/oauth/authorize
    resource:
      user-info-uri: http://localhost:9090/app/principal